### PR TITLE
#167124414 Failing tests for new repair request

### PR DESCRIPTION
**Pull request by masakhwe**
### What does this PR do?
Runs tests that ensure proper and successful registration a user's new repair request

### What are the tasks to be completed?

- Ensure new repair request page/form loads successfully

- Ensure the right template is used

- Ensure repair request details are successfully saved to the database

- Ensure the user is redirected to the home page upon successful registration of a new repair request

### How Should this be manually tested?
Create a virtual environment
`Virtualenv venv`

Clone the repo
`git clone https://github.com/masakhwe/RepairHub.git`

Checkout to failing tests branch
`git checkout ft-failing-tests-for-new-repair-request-167124414`

Install the dependencies
`pip install -r requirements.txt`

Run pytest
`pytest -v`

Screenshots
failing_tests_repair_request

passing_tests_new_repair_request

new_repair_request

repair_request_saved

### What are the relevant pivotal tracker stories
[#167124414](https://www.pivotaltracker.com/story/show/167124414)
[#167124581](https://www.pivotaltracker.com/story/show/167124581)

### CODE REVIEW

**Comment by PaulKitonyi** [comment]
Hey Mark.Previously you had four tests passing and now can see you have added some other five.So by now you should be having 9 tests passing!!Where are the rest???

**Comment by masakhwe** [comment]
I errored by only running tests partaining to this branch and skipped the rest. I will run all the 15 tests and attach the screenshot.

**Comment by masakhwe** [comment]
Removed the owner field from the new repair request form as observed in the screenshot below
new_repair_request

**Comment by PaulKitonyi** [comment]
Wow, nice PR and great work!! Keep it up man.

**Pull request closed without merging**
